### ISSUE TITLE
Maybe git LFS wasn't such a good idea :( 

### ISSUE THREAD

**Issue by twogood** [twogood/unshield#161]
```
failed to fetch some objects from 'https://github.com/twogood/unshield.git/info/lfs
```

https://github.com/twogood/unshield/actions/runs/2490089088

**Comment by kratz00** [comment]
```
  batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
  Error: error: failed to fetch some objects from 'https://github.com/twogood/unshield.git/info/lfs'
```

The free plan only allows for 1 GB/month of bandwidth :cry: 
So every time the repository is cloned (which includes the CI jobs) this will add up to the 1 GB/month.
See https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-storage-and-bandwidth-usage for more information
Instead of paying 5 Dollars per month to have 50 GB, we could add the test data files back as Git objects instead of using Git LFS.
If I am not mistaken the test data files are around 50 MB and they will not change, meaning the repository and it's history will be  affected only a little.

If there are no objections I will send a pull request and remove the Git LFS integration for this repository.
